### ISSUE TITLE
关于英文文献引用的格式

### ISSUE THREAD

**Issue by yizhiwang96** [xelmirage/pku_thesis_docx#1]
关于英文文献引用的格式，有官方说明吗？主要是名字的写法，会议和期刊的写法不太确定。

**Comment by xelmirage** [comment]
请参阅GB /T 7714—2015

从 Windows 版邮件发送

发件人: Yizhi Wang
发送时间: 2022年4月7日 17:31
收件人: xelmirage/pku_thesis_docx
抄送: Subscribed
主题: [xelmirage/pku_thesis_docx] 关于英文文献引用的格式 (Issue #1)

关于英文文献引用的格式，有官方说明吗？主要是名字的写法，会议和期刊的写法不太确定。
