### ISSUE TITLE
自己插入题注时，图序发生变化

### ISSUE THREAD

**Issue by llstela** [xelmirage/pku_thesis_docx#2]
按照文档说明，复制原有的题注，可以正常使用：
<img src="https://github.com/xelmirage/pku_thesis_docx/assets/72986883/ab25bf93-c9e1-49a6-9c5f-5b890b3df11a" alt="复制的题注" width="500">

当尝试自己加入题注时，会出现如下现象：
<img src="https://github.com/xelmirage/pku_thesis_docx/assets/72986883/08e48dc3-78dc-4b79-bcbc-fd32a78f11fd" alt="复制的题注" width="500">

虽然可以避免，但个人比较好奇这个问题的来源。

**Comment by xelmirage** [comment]
为了实现图编号里带章节编号，图编号的域代码有修改，自己插入的话可能是系统预制的域代码，会有预期外的行为
