### ISSUE TITLE
部分样式字体消失的情况

### ISSUE THREAD

**Issue by llstela** [xelmirage/pku_thesis_docx#3]
## 使用WPS打开模板，在参考文献处的样式显示为 EndNote Bibliography:
<img src="https://github.com/xelmirage/pku_thesis_docx/assets/72986883/b8dab836-c897-4ff0-a111-c12352f3b3cc" alt="WPS" width="600">

## 但是使用 Word 2021 LTSC 打开时，没有找到对应的样式，虽然字体和字号是对应的：
<img src="https://github.com/xelmirage/pku_thesis_docx/assets/72986883/98ba4a30-a6fa-4e8f-8e51-a81e98356675" alt="Word2021LTSC" width="600">

**Comment by xelmirage** [comment]
[https://zhidao.baidu.com/question/1771164705929717300.html](https://zhidao.baidu.com/question/1771164705929717300.html)
